Repository cofide/cofidectl, pull requests merged in 2025-05, with the labels that each got.

#228 fix: install Helm secrets into spire-mgmt namespace
  pkg/provider/helm/helm.go
  tests/integration/single-trust-zone/test.sh
Labels: bug

#224 feat: Add GetHelmValues method to Provision interface
  cmd/cofidectl/cmd/trustzone/helm/helm.go
  go.mod
  go.sum
  pkg/plugin/provision/interface.go
  pkg/plugin/provision/plugin.go
  pkg/plugin/provision/plugin_test.go
  pkg/plugin/provision/spirehelm/providerfactory.go
  pkg/plugin/provision/spirehelm/spirehelm.go
  pkg/plugin/provision/spirehelm/spirehelm_test.go
  tests/integration/federation/test.sh
Labels: feature

#226 fix: add a --force argument to trust zone and cluster delete
  cmd/cofidectl/cmd/cluster/cluster.go
  cmd/cofidectl/cmd/federation/federation.go
  cmd/cofidectl/cmd/trustzone/trustzone.go
  cmd/cofidectl/cmd/trustzone/trustzone_test.go
  cmd/cofidectl/cmd/workload/workload.go
  pkg/provider/helm/helm.go
Labels: bug

#237 fix: federation deletion with local data source
  pkg/plugin/local/local.go
Labels: bug

#238 chore: Bump SPIRE Helm chart versions
  internal/pkg/trustprovider/trustprovider.go
  pkg/provider/helm/helm.go
  pkg/provider/helm/helm_test.go
  pkg/provider/helm/values.go
  pkg/provider/helm/values_test.go
  pkg/spire/spire_server_cli.go
Labels: chore
